services:
  staging:
    build:
      context: ../
      dockerfile: .docker/staging/Dockerfile
    extends:
      file: compose.common.yml
      service: host_base
    hostname: staging
    links:
      - registry
    depends_on:
      - registry
    ports:
      - "1251:22"
    profiles: ["", staging]
    networks:
      - registry_net
      - staging_net
    volumes:
      - staging_dind_vol:/var/lib/docker
      - staging_certs:/certs
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4GB
        reservations:
          cpus: "1"
          memory: 1G
    healthcheck:
      test: nc -z localhost 22 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  host:
    build:
      context: ../
      dockerfile: .docker/host/Dockerfile
    extends:
      file: compose.common.yml
      service: host_base
    hostname: host
    ports:
      - "1250:22"
    profiles: ["", host]
    links:
      - staging
    networks:
      - staging_net
      - registry_net
    volumes:
      - host_dind_vol:/var/lib/docker
      - host_certs:/certs
    healthcheck:
      test: nc -z localhost 22 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  registry:
    build:
      context: ./registry/
      dockerfile: ./Dockerfile
    extends:
      file: compose.common.yml
      service: config
    hostname: "registry"
    restart: always
    env_file:
      - path: ../.env
        required: true
      - path: ../.env.local
        required: false
    profiles: ["", staging]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - registry_net
    healthcheck:
      test: nc -z localhost 5000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  staging_dind_vol:
  staging_certs:
  host_dind_vol:
  host_certs:
  user_ssh:
  ssh_config:

networks:
  registry_net:
    driver: bridge
  staging_net:
    driver: bridge
