services:
  test:
    container_name: docker_cicd_test
    build:
      context: ./../
      dockerfile: .docker/test/Dockerfile
      args:
        - SSH_PASSWORD=KollaneHobune
    extends:
      file: compose.common.yml
      service: config
    hostname: test
    env_file: !override [../.env.test]
    links:
      - staging
      - host:production
    depends_on:
      - staging
      - host
    profiles: []
    networks:
      - staging_net

  staging:
    container_name: docker_cicd_test_staging
    build:
      args:
        - SSH_PASSWORD=KollaneHobune
    env_file: !override [../.env.test]
    profiles: []
    ports: !reset []
    
  registry:
    container_name: docker_cicd_test_registry
    env_file: !override [../.env.test]
    profiles: []

  host:
    container_name: docker_cicd_test_host
    build:
      args:
        - SSH_PASSWORD=KollaneHobune
    env_file: !override [../.env.test]
    profiles: []
    ports: !reset []