services:
  test:
    build:
      context: ./../
      dockerfile: .docker/test/Dockerfile
      args:
        - SSH_PASSWORD=KollaneHobune
    extends:
      file: compose.common.yml
      service: config
    hostname: test
    env_file: !override [../.env.test]
    links:
      - staging
      - host:production
    depends_on:
      - staging
      - host
    profiles: [test]
    networks:
      - staging_net

  staging:
    build:
      args:
        - SSH_PASSWORD=KollaneHobune
    env_file: !override [../.env.test]
    profiles: [test]
    ports: !reset []
    
  registry:
    env_file: !override [../.env.test]
    profiles: [test]

  host:
    build:
      args:
        - SSH_PASSWORD=KollaneHobune
    env_file: !override [../.env.test]
    profiles: [test]
    ports: !reset []