services:
  staging:
    build:
      context: ../
      dockerfile: .docker/staging/Dockerfile
    extends:
      file: compose.common.yml
      service: host_base
    hostname: staging
    links:
      - registry
    depends_on:
      - registry
    ports:
      - "1251:22"
    profiles: ["", staging]
    networks:
      - registry_net
      - staging_net
    volumes:
#      - ./staging/bin/stage:/usr/local/bin/stage
      - ../env:/var/docker_cicd/env:ro
      - /var/tests:/var/tests
      - staging_app_vol:/app
      - staging_dind_vol:/var/lib/docker
      - staging_certs:/certs
    healthcheck:
      test: >
        nc -z localhost 22 || exit 1;
        docker info > /dev/null 2>&1 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  host:
    build:
      context: ../
      dockerfile: .docker/host/Dockerfile
    extends:
      file: compose.common.yml
      service: host_base
    hostname: host
    ports:
      - "1250:22"
    profiles: ["", host]
    depends_on:
      - staging
    links:
      - staging
    networks:
      - registry_net
      - staging_net
    volumes:
#      - ./host/bin/deploy:/usr/local/bin/deploy
      - ../env:/var/docker_cicd/env:ro
      - host_app_vol:/app
      - host_dind_vol:/var/lib/docker
      - host_certs:/certs
    healthcheck:
      test: >
        nc -z localhost 22 || exit 1;
        docker info > /dev/null 2>&1 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  registry:
    build:
      context: ./registry/
      dockerfile: ./Dockerfile
    extends:
      file: compose.common.yml
      service: config
    hostname: "registry"
    restart: always
    env_file:
      - path: ../.env
        required: true
      - path: ../.env.local
        required: false
    environment:
      - REGISTRY_LOG_LEVEL=warn
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    profiles: ["", staging]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - registry_net
    volumes:
      - registry_dind_vol:/var/lib/registry
    healthcheck:
      test: nc -z localhost 5000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M

volumes:
  staging_app_vol:
  staging_dind_vol:
  staging_certs:
  host_app_vol:
  host_dind_vol:
  registry_dind_vol:
  host_certs:
  user_ssh:
  ssh_config:

networks:
  registry_net:
    driver: bridge
  staging_net:
    driver: bridge
