services:
  app:
    build:
      context: ../
      dockerfile: .docker/app/Dockerfile
    image: localhost:5000/test_repo:${VERSION:-local}
    container_name: test_repo
    hostname: test_repo
    env_file: ../.env
    ports:
      - "0:8765"
    networks:
      - demo_net
    volumes:
      - test_app_volume:/app/volume

volumes:
  test_app_volume:

networks:
  demo_net:
    driver: bridge