services:
  config:
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: '5'
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2GB
        reservations:
          cpus: "1"
          memory: 512M

  host_base:
    build:
      context: ../
      dockerfile: .docker/staging/Dockerfile
    extends:
      file: compose.common.yml
      service: config
    command: /usr/sbin/sshd -D -e > /dev/stdout 2>/dev/stderr &
    env_file:
      - path: ../.env
        required: true
      - path: ../.env.local
        required: false
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    ports:
#      - "1248:22"
#      - "2376:2376" # Docker daemon port (if needed)
    privileged: true
    environment:
#      - DOCKER_CGROUPS=/sys/fs/cgroup
#      - DOCKER_HOST=tcp://localhost:2376  # Set Docker host to the DinD service
#      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_CERTDIR=
    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup
      - ssh_config:/etc/ssh
      - user_ssh:/home/cicd/.ssh
      - /var/lib/docker