services:
  app:
    build:
      context: ../
      dockerfile: .docker/app/Dockerfile
    image: localhost:5000/test_repo:${VERSION:-local}
    container_name: test_repo
    hostname: test_repo
    restart: unless-stopped
    env_file: ../.env