services:
  config:
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M
          
  host_base:
    build:
      context: ../
      dockerfile: .docker/staging/Dockerfile
    extends:
      file: compose.common.yml
      service: config
    command: /usr/sbin/sshd -D -e > /dev/stdout 2>/dev/stderr &
    env_file:
      - path: ../.env
        required: true
      - path: ../.env.local
        required: false
    restart: always
#    ports:
#      - "1248:22"
##      - "2375:2375" # Docker daemon port (if needed)
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
#      - docker_dind_vol:/var/lib/docker # Persist Docker data
      - certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh_config:/etc/ssh
      - user_ssh:/home/cicd/.ssh
      - backups_vol:/var/backups/digicmr